# Generated by Django 3.2.8 on 2022-03-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroommember',
            old_name='room',
            new_name='chatRoom',
        ),
    ]
