# Generated by Django 3.2.8 on 2022-03-14 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroommessage_postedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommessage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroommember'),
        ),
    ]
